CREATE SCHEMA DIEGOMARKS3;
COMMIT;

CREATE TABLE DIEGOMARKS3.CLIENTE(
ID_CLIENTE INTEGER NOT NULL,
NOME VARCHAR(45)
);
COMMIT;
ALTER TABLE DIEGOMARKS3.CLIENTE ADD CONSTRAINT
PK_CLIENTE PRIMARY KEY (ID_CLIENTE);
COMMIT;
ALTER TABLE DIEGOMARKS3.CLIENTE DROP COLUMN TELEFONE;
INSERT INTO DIEGOMARKS3.CLIENTE(ID_CLIENTE,NOME) VALUES
(1,'DIEGO MARKS');
COMMIT;
SELECT * FROM DIEGOMARKS3.CLIENTE;




DROP TABLE DIEGOMARKS3.CLIENTE_VIP;
CREATE TABLE DIEGOMARKS3.CLIENTE_VIP(
ID_CLIENTE INTEGER NOT NULL,
DESCONTO_PADRAO FLOAT NOT NULL
);
COMMIT;
ALTER TABLE DIEGOMARKS3.CLIENTE_VIP ADD CONSTRAINT
FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE)
REFERENCES DIEGOMARKS3.CLIENTE (ID_CLIENTE);
COMMIT;
INSERT INTO DIEGOMARKS3.CLIENTE_VIP(ID_CLIENTE,DESCONTO_PADRAO) VALUES
(1,3.400);




CREATE TABLE DIEGOMARKS3.CLIENTE_PADRAO(
ID_CLIENTE INTEGER NOT NULL,
DESCONTO_PADRAO FLOAT
);
COMMIT;
ALTER TABLE DIEGOMARKS3.CLIENTE_PADRAO ADD CONSTRAINT
FK_ID_CLIENTE_PADRAO FOREIGN KEY (ID_CLIENTE)
REFERENCES DIEGOMARKS3.CLIENTE (ID_CLIENTE);
COMMIT;
INSERT INTO DIEGOMARKS3.CLIENTE_PADRAO(DESCONTO_PADRAO, ID_CLIENTE) VALUES
(13.54,2);
COMMIT;




CREATE TABLE DIEGOMARKS3.TELEFONE(
TELEFONE VARCHAR(14)
);
COMMIT;
ALTER TABLE DIEGOMARKS3.TELEFONE ADD COLUMN ID_CLIENTE INTEGER;
SELECT * FROM DIEGOMARKS3.TELEFONE;
ALTER TABLE DIEGOMARKS3.TELEFONE ADD CONSTRAINT
FK_TELEFONE_CLIENTE FOREIGN KEY (ID_CLIENTE)
REFERENCES DIEGOMARKS3.CLIENTE (ID_CLIENTE);
COMMIT;
INSERT INTO DIEGOMARKS3.TELEFONE(ID_CLIENTE, TELEFONE) VALUES
(1,'999315752');
COMMIT;




CREATE TABLE DIEGOMARKS3.ENDERECO(
ID_ENDERECO INTEGER NOT NULL,
RUA VARCHAR(45),
CIDADE VARCHAR(45),
ESTADO VARCHAR(45),
CEP VARCHAR(45),
ID_CLIENTE INTEGER NOT NULL
);
COMMIT;
ALTER TABLE DIEGOMARKS3.ENDERECO ADD CONSTRAINT
PK_ENDERECO PRIMARY KEY (ID_ENDERECO);
ALTER TABLE DIEGOMARKS3.ENDERECO ADD CONSTRAINT
FK_CLIENTE_ENDERECO FOREIGN KEY (ID_CLIENTE)
REFERENCES DIEGOMARKS3.CLIENTE (ID_CLIENTE);
COMMIT;
INSERT INTO DIEGOMARKS3.ENDERECO(CEP, CIDADE, ESTADO, ID_CLIENTE, ID_ENDERECO, RUA) VALUES
('85760-000','CAPANEMA','PARANÁ',1,1,'RUA GUARANI');
COMMIT;




CREATE TABLE DIEGOMARKS3.PEDIDO(
ID_PEDIDO INTEGER NOT NULL,
DATA_PEDIDO DATE,
DATA_ENTREGA DATE,
ID_ENDERECO INTEGER NOT NULL,
ID_CLIENTE INTEGER NOT NULL
);
COMMIT;
ALTER TABLE DIEGOMARKS3.PEDIDO ADD CONSTRAINT
PK_PEDIDO PRIMARY KEY (ID_PEDIDO);
ALTER TABLE DIEGOMARKS3.PEDIDO ADD CONSTRAINT
FK_ENDERECO_PEDIDO FOREIGN KEY (ID_ENDERECO)
REFERENCES DIEGOMARKS3.ENDERECO (ID_ENDERECO);
ALTER TABLE DIEGOMARKS3.PEDIDO ADD CONSTRAINT
FK_CLIENTE_PEDIDO FOREIGN KEY (ID_CLIENTE)
REFERENCES DIEGOMARKS3.CLIENTE (ID_CLIENTE);
COMMIT;
SELECT * FROM DIEGOMARKS3.PEDIDO;

INSERT INTO DIEGOMARKS3.PEDIDO(DATA_ENTREGA, DATA_PEDIDO, ID_CLIENTE, ID_ENDERECO, ID_PEDIDO) VALUES
(15/03/2022,14/02/2022,1,1,1);



CREATE TABLE DIEGOMARKS3.MERCADORIA(
ID_MERCADORIA INTEGER NOT NULL,
PRECO FLOAT,
ICMS FLOAT
);
COMMIT;
ALTER TABLE DIEGOMARKS3.MERCADORIA ADD CONSTRAINT
PK_MERCADORIA PRIMARY KEY (ID_MERCADORIA);




CREATE TABLE DIEGOMARKS3.ITEM_PEDIDO(
ID_PEDIDO INTEGER NOT NULL,
QUANTIDADE INTEGER,
DESCONTO FLOAT,
ID_MERCADORIA INTEGER NOT NULL
);
COMMIT;
ALTER TABLE DIEGOMARKS3.ITEM_PEDIDO ADD CONSTRAINT
FK_PEDIDO_ITEM FOREIGN KEY (ID_PEDIDO)
REFERENCES DIEGOMARKS3.PEDIDO (ID_PEDIDO);
ALTER TABLE DIEGOMARKS3.ITEM_PEDIDO ADD CONSTRAINT
FK_PEDIDO_MERCADORIA FOREIGN KEY (ID_MERCADORIA)
REFERENCES DIEGOMARKS3.MERCADORIA (ID_MERCADORIA);
COMMIT
