DROP TABLE MARKS.TIPO_TARIFA
COMMIT

CREATE TABLE MARKS.UNIDADE_CONSUMO(
        ID_UNIDADE_CONSUMO INTEGER NOT NULL,
        MATRICULA VARCHAR(11),
        ENDERECO VARCHAR(45),
        ID_TIPO_TAFIRA INTEGER NOT NULL
);
COMMIT


CREATE TABLE MARKS.TIPO_TARIFA(
        ID_TIPO_TARIFA INTEGER NOT NULL,
        DESCO_TIPO_TARIFA VARCHAR(45)
);
COMMIT


CREATE TABLE MARKS.CONSUMO(
        ID_CONSUMO INTEGER NOT NULL,
        QUANTIDADE FLOAT,
        MES INTEGER,
        ANO INTEGER,
        ID_UNIDADE_CONSUMO INTEGER NOT NULL
);
COMMIT


ALTER TABLE MARKS.UNIDADE_CONSUMO ADD CONSTRAINT
FK_TIPO_TARIFA_IDM FOREIGN KEY (ID_TIPO_TARIFA)
REFERENCES MARKS.TIPO_TARIFA (ID_TIPO_TARIFA);
COMMIT


ALTER TABLE MARKS.CONSUMO ADD CONSTRAINT
FK_UNDCON_IDTAR FOREIGN KEY (ID_UNIDADE_CONSUMO)
REFERENCES MARKS.UNIDADE_CONSUMO(ID_UNIDADE_CONSUMO);
COMMIT

----------------------------------------------------------------
CRIANDO NOVA SCHEMA


CREATE SCHEMA DIEGOMARKS
COMMIT



CREATE TABLE DIEGOMARKS.EMPRESA(
IDEMPRESA INTEGER NOT NULL,
CNPJ VARCHAR(14),
NOMEFANTASIA VARCHAR(20),
RAZAOSOCIAL VARCHAR(20),
UF VARCHAR(2)
);
COMMIT
ALTER TABLE DIEGOMARKS.EMPRESA ADD CONSTRAINT
PK_EMPRESA PRIMARY KEY (IDEMPRESA);
COMMIT



CREATE TABLE DIEGOMARKS.CLIENTE(
IDCLIENTE INTEGER NOT NULL,
CPF VARCHAR(11),
NOME VARCHAR(20),
ENDERECO VARCHAR(25),
UF VARCHAR(2)
);
COMMIT
ALTER TABLE DIEGOMARKS.CLIENTE ADD CONSTRAINT
PK_CLIENTE PRIMARY KEY (IDCLIENTE);
COMMIT



CREATE TABLE DIEGOMARKS.PRODUTO(
IDPRODUTO INTEGER NOT NULL,
DESCRICAOPRODUTO VARCHAR(30),
PRECO FLOAT,
CODIGOBARRAS VARCHAR(43)
);
COMMIT
ALTER TABLE DIEGOMARKS.PRODUTO ADD CONSTRAINT
PK_PRODUTO PRIMARY KEY (IDPRODUTO);
COMMIT

CREATE TABLE DIEGOMARKS.VENDEDOR(
IDVENDEDOR INTEGER NOT NULL,
NOME VARCHAR(20),
COMISSAO FLOAT
);
COMMIT
ALTER TABLE DIEGOMARKS.VENDEDOR ADD CONSTRAINT
PK_VENDEDOR PRIMARY KEY (IDVENDEDOR);
COMMIT

-----------------------------------------------------------
NOTA FISCAL COM SEUS FK
-----------------------------------------------------------
CREATE TABLE DIEGOMARKS.NOTAFISCAL(
IDNOTAFISCAL INTEGER NOT NULL,
VALORTOTAL FLOAT,
IDVENDEDOR INTEGER NOT NULL,
IDCLIENTE INTEGER NOT NULL,
IDEMPRESA INTEGER NOT NULL
);
COMMIT
ALTER TABLE DIEGOMARKS.NOTAFISCAL ADD CONSTRAINT
PK_NOTAFISCAL PRIMARY KEY (IDNOTAFISCAL);
COMMIT
ALTER TABLE DIEGOMARKS.NOTAFISCAL ADD CONSTRAINT
FK_VENDEDOR_FK FOREIGN KEY (IDVENDEDOR)
REFERENCES DIEGOMARKS.VENDEDOR (IDVENDEDOR);
ALTER TABLE DIEGOMARKS.NOTAFISCAL ADD CONSTRAINT
FK_CLIENTE_FK FOREIGN KEY (IDCLIENTE)
REFERENCES DIEGOMARKS.CLIENTE (IDCLIENTE);
ALTER TABLE DIEGOMARKS.NOTAFISCAL ADD CONSTRAINT
FK_EMPRESA_FK FOREIGN KEY (IDEMPRESA)
REFERENCES DIEGOMARKS.EMPRESA (IDEMPRESA);
COMMIT
-----------------------------------------------------

CREATE TABLE DIEGOMARKS.NOTAFISCALPRODUTO(
NUMERONOTAFISCAL INTEGER NOT NULL,
IDPRODUTO INTEGER NOT NULL,
VALOR INTEGER,
QUANTIDADE INTEGER
);
COMMIT
ALTER TABLE DIEGOMARKS.NOTAFISCALPRODUTO ADD CONSTRAINT
PK_NOTAFISCAL PRIMARY KEY (NUMERONOTAFISCAL);
COMMIT
ALTER TABLE DIEGOMARKS.NOTAFISCALPRODUTO ADD CONSTRAINT
FK_PRODUTO_FK2 FOREIGN KEY (IDPRODUTO)
REFERENCES DIEGOMARKS.PRODUTO (IDPRODUTO);
COMMIT




